<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>Test sample_SUITE:test2 result</title>
<meta http-equiv="cache-control" content="no-cache"></meta>
<meta http-equiv="content-type" content="text/html; charset=utf-8"></meta>
<link rel="stylesheet" href="../../ct_default.css" type="text/css"></link>
<script type="text/javascript" src="../../jquery-latest.js"></script>
<script type="text/javascript" src="../../jquery.tablesorter.min.js"></script>
</head>
<body>

<a name="top"></a><pre>
=== Test case: <a href="sample_suite.src.html#test2-1">sample_SUITE:test2/1</a> (click for source code)

=== Config value:

    [{watchdog,&lt;0.398.0&gt;},
     {tc_logfile,"c:/Users/Wai Chung Fung/Desktop/Class 2017-18/CMPT 436/cmpt436project/test/logs/ct_run.nonode@nohost.2017-12-03_15.43.42/test.suites.logs/run.2017-12-03_15.43.44/sample_suite.test2.html"},
     {tc_group_properties,[{suite,sample_SUITE}]},
     {tc_group_path,[]},
     {data_dir,"c:/Users/Wai Chung Fung/Desktop/Class 2017-18/CMPT 436/cmpt436project/test/suites/sample_SUITE_data/"},
     {priv_dir,"c:/Users/Wai Chung Fung/Desktop/Class 2017-18/CMPT 436/cmpt436project/test/logs/ct_run.nonode@nohost.2017-12-03_15.43.42/test.suites.logs/run.2017-12-03_15.43.44/log_private/"}]

=== Current directory is "c:/Users/Wai Chung Fung/Desktop/Class 2017-18/CMPT 436/cmpt436project/test/logs/ct_run.nonode@nohost.2017-12-03_15.43.42"

=== Started at 2017-12-03 15:43:46

<br />

</pre>
<div class="ct_error_notify"><pre><b>*** CT Error Notification 2017-12-03 15:43:46.738 ***</b>
sample_SUITE:test2 failed on line 17
Reason: badarith

<a href="#end">Full error description and stacktrace</a>
</pre></div>
<pre>
<a name="end"></a>


=== Ended at 2017-12-03 15:43:46
=== Location: [{sample_SUITE,test2,<a href="sample_suite.src.html#17">17</a>},
              {test_server,ts_tc,1539},
              {test_server,run_test_case_eval1,1055},
              {test_server,run_test_case_eval,987}]
=== Reason: an error occurred when evaluating an arithmetic expression
  in function  sample_SUITE:test2/1 (test/suites/sample_SUITE.erl, line 17)
  in call from test_server:ts_tc/3 (test_server.erl, line 1539)
  in call from test_server:run_test_case_eval1/6 (test_server.erl, line 1055)
  in call from test_server:run_test_case_eval/9 (test_server.erl, line 987)
</pre>
<center>
<br /><hr /><p>
<a href="../../../all_runs.html">Test run history
</a>  |  <a href="../../../index.html">Top level test index
</a>
</p>
<div class="copyright">Copyright &copy; 2017 <a href="http://www.erlang.org">Open Telecom Platform</a><br />
Updated: <!--date-->Sun Dec 03 2017 15:43:46<!--/date--><br />
</div>
</center>
</body>
</html>
